CREATE OR REPLACE VIEW {view_name} AS
SELECT *
FROM {candidates_table}
WHERE issue_type IN (
    'HIGH_COST_LOW_UTILIZATION',
    'LOW_UTILIZATION',
    'MEMORY_BOUND',
    'SHARED_CLUSTER_ATTRIBUTION',
    'UNKNOWN_ATTRIBUTION',
    'HIGH_FAILURE_COST',
    'HIGH_FAILURE_RATE',
    'RETRY_HEAVY'
)
ORDER BY priority_rank
